# NOTE(mroberts): https://github.com/travis-ci/travis-ci/issues/4704
filter_secrets: false

sudo: false

language: generic

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    # NOTE(mroberts): See https://github.com/markandrus/twilio-haskell/issues/44
    # - env: BUILD=cabal CABALVER=1.18 GHCVER=7.8.4
    #   compiler: ": #GHC 7.8.4"
    #   addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}

    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.1
      compiler: ": #GHC 7.10.1"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}

    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.2
      compiler: ": #GHC 7.10.2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}

    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

    - env: BUILD=cabal CABALVER=3.6.2 GHCVER=9.0.2
      compiler: ": #GHC 9.0.2"
      addons: {apt: {packages: [cabal-install-3.6.2.0,ghc-9.0.2], sources: [hvr-ghc]}}

    - env: BUILD=cabal CABALVER=3.6.2 GHCVER=9.2.4
      compiler: ": #GHC 9.2.4"
      addons: {apt: {packages: [cabal-install-3.6.2.0,ghc-9.2.4], sources: [hvr-ghc]}}

    # NOTE(mroberts): I've borrowed this from Yesod's .travis.yml:
    #
    #     https://github.com/yesodweb/yesod/blob/master/.travis.yml
    #
    - env: BUILD=stack ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev]}}

    # NOTE(mroberts): I'd like to support 7.8.4, but AMP makes this annoying.
    # Take this up later, e.g. with base-compat.
    # - env: BUILD=stack ARGS="--resolver lts-2"
    #   compiler: ": #stack 7.8.4"
    #   addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-3"
      compiler: ": #stack 7.10.2"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-6"
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-7"
      compiler: ": #stack 8.0.1"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-8"
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-9"
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-10"
      compiler: ": #stack 8.2.2"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-11"
      compiler: ": #stack 8.2.2"
      addons: {apt: {packages: [libgmp-dev]}}

    - env: BUILD=stack ARGS="--resolver lts-19"
      compiler: ": #stack 9.0.2"
      addons: {apt: {packages: [libgmp-dev]}}

before_install:
 - unset CC
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - |
   set -ex
   if [ "$ARGS" = "--resolver nightly" ]
   then
     stack --install-ghc $ARGS build cabal-install
     stack --install-ghc $ARGS solver --update-config
   fi
   set +ex

script:
 - |
   set -ex
   case "$BUILD" in
     stack)
       stack --install-ghc --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps --ghc-options="-Wall -Werror -fno-warn-name-shadowing -fno-warn-orphans -fno-warn-unticked-promoted-constructors -fno-warn-unused-do-bind"
       ;;
     cabal)
       cabal --version
       travis_retry cabal update
       sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
       cabal install --dependencies-only --enable-tests --enable-benchmarks
       cabal configure --enable-tests --enable-benchmarks -v2
       cabal build
       cabal test
       cabal sdist
       SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
       ;;
   esac
   set +ex

after_success:
  - script/publish_haddock.sh
